### ISSUE TITLE
Multi title-bar issue if Yume 2kki Navigator is enabled

### ISSUE THREAD

**Issue by Shakzass** [joaovitorbf/ynodesktop#11]
**Issue:** 
An unlimited amount of title bars appear when enabling the Yume 2kki Navigator option in the settings, regardless of whether it's toggled ON or OFF. Each new title bar corresponds to a new page of the navigator being loaded, starting with one singular title bar on the title screen, two bars on the real room, and so on.

This does not happen if the Yume 2kki Navigator option is disabled. Enabling the option mid-game still causes issues

**Steps to reproduce:** 
1. Enable the option "Yume 2kki Navigator" in the settings menu. 
2. Start or continue a new game.
3. A new title bar should have appeared.
4. More title bars can be created by accessing different worlds. 

**Yume 2kki Navigator disabled:**
![image](https://github.com/joaovitorbf/ynodesktop/assets/74895531/63ead2dd-a3e6-45a0-931a-6bba89dd7296)

**Yume 2kki Navigator enabled:**
![image](https://github.com/joaovitorbf/ynodesktop/assets/74895531/c7fc6071-2c8b-4f8e-b92b-7595485f01aa)

**Comment by joaovitorbf** [comment]
Thank you for the complete issue report. This should now be fixed on release 1.1.5.
