### ISSUE TITLE
Zooming out for smaller screens?

### ISSUE THREAD

**Issue by fishjoshi** [joaovitorbf/ynodesktop#14]
I enjoy playing 2kki on my 4:3 CRT just because it looks neat, problem is the chat is kinda difficult to access this way, is there a way to zoom out so its on the side? 

(I know this isn't necessary and it's my problem for using a CRT lol I was just wondering if theres a way I can fix that, eitherway thanks for creating ynodesktop it's awesome ^^)

**Comment by joaovitorbf** [comment]
Hello! Thanks for your suggestion!
I have added a zoom in and out button to the context menu (right click) on the newest release (1.1.7), I hope that helps with your issues viewing the game on a CRT screen. Cool idea, by the way. I need a CRT monitor.
