### ISSUE TITLE
Glitchy audio

### ISSUE THREAD

**Issue by Nassim0** [joaovitorbf/ynodesktop#3]
The audio keeps stuttering and just being messy overall. Any news on that?

**Comment by joaovitorbf** [comment]
I can't replicate this issue as the audio is fine for me.
Is there something that happens in-game or in the interface that seems to be causing this? Or is it just choppy all the time?

**Comment by joaovitorbf** [comment]
Closing for now as that doesn't seem to be happening anymore?
