### ISSUE TITLE
idkk

### ISSUE THREAD

**Issue by xoffoki** [joaovitorbf/ynodesktop#7]
https://github.com/joaovitorbf/ynodesktop/assets/88249224/65f239b2-59b5-45ba-868b-c38e3981dc38

only in 2kki
this happened in the previous version as well

**Comment by Nisshisora** [comment]
Happens to me on my end too. Sometimes it does a lot, sometimes it does a few. The toolbar just seems to duplicate itself.

**Comment by Nep-Timeline** [comment]
try this #8 :)
